type Buyer = {
    buyerOrganisationName?: string | null,
    buyerOrganisationName2?: string | null,
    countryCode?: string | null,
    countryName?: string,
    postCodeIdentifier?: string | null,
    streetName?: string | null,
    streetName2?: string | null,
    townName?: string | null,
}
  
type Recipient = {
    countryCode?: string | null,
    contryName?: string,
    postCodeIdentifier?: string | null,
    recipientOrganisationName?: string | null,
    recipientOrganisationName2?: string | null,
    streetName?: string | null,
    streetName2?: string | null,
    townName?: string | null,
}

type SalesOrder = {
    accountDimension?: string | null,
    accountDimension2?: string | null,
    accountDimension3?: string | null,
    accountDimension4?: string | null,
    changeTime?: string,
    changeUser?: string,
    description: string | null,
    discrountRate?: number,
    internalDescription?: string,
    productCode: string | null,
    quantity?: number,
    rowFreeText: string | null,
    textRow?: boolean,
    unitPriceExcludingTaxt?: number,
    totalSumIncludingTax?: number,
    unitId?: string | null
}

export type Invoice = {
    accountDimensionText?: string | null,
    agreementIdentifier?: string | null,
    buyer?: Buyer,
    buyerReferenceIdentifier?: string | null,
    changeTime?: string,
    changeUser?: string,
    createTime?: string,
    createUser?: string,
    cuid: string | null,
    currency: string,
    currencyRate: number,
    customerId: string,
    deliverDate?: string | null,
    id?: string | null,
    externalOrderNumber?: string | null,
    externalBatchId?: string | null,
    deliveryTermId?: string | null,
    deliveryDate?: string | null,
    deliveryMethodId?: string | null,
    invoiceReference?: string | null,
    languageCode?: string | null,
    orderIdentifier?: string | null,
    orderDate?: string | null,
    orderNumber?: string | null,
    orderStatus?: string | null,
    paymentTermId?: string | null,
    postingGroupId?: string,
    readyToInvoice?: boolean,
    recipient?: Recipient,
    salesOrderRowDTOS?: SalesOrder[],
    salesPersonId?: string | null
    tenderReference?: string | null,
    totalVatAmount?: number,
    totalVatExcludedAmount?: number,
    totalVatIncludedAmount?: number,
    transmissionTypeId?: string | null,
}