name: CI

on: 
  push:
    branches:
      - main
      - pipeline_test
  pull_request:
    branches:
      - main
    types: 
      - opened

jobs: 
  build_pipeline:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: 
        node-version: '16'
    - name: build
      run: npm run test
